users:
  index:
    size: 50
size: 100
time: 2
name:
  maximum: 50
password:
  minimum: 6
email:
  maximum: 255
concerns:
  users_controller:
    page: 5
micropost:
  maximum: 140
avatarpost:
  size: 50
posts_controller:
    page: 10
sizes:
  image: 5
